server {
    listen 80;
    server_name PLACEHOLDER_SERVER_NAME;

    root PLACEHOLDER_WEB_ROOT;
    index index.html;

    add_header Content-Security-Policy "default-src 'self'; img-src 'self'; style-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

    location = /vocabularios {
        try_files /vocabularios/index.html =404;
    }

    location = /vocabularios/seaes {
        try_files /vocabularios/seaes/index.html =404;
    }

    location = /vocabularios/seaes.ttl {
        default_type text/turtle;
        try_files /vocabularios/seaes.ttl =404;
    }

    location = /vocabularios/seaes.jsonld {
        default_type application/ld+json;
        try_files /vocabularios/seaes.jsonld =404;
    }

    location = /esquemas {
        try_files /esquemas/index.html =404;
    }

    location = /esquemas/metadatos {
        try_files /esquemas/metadatos/index.html =404;
    }

    location = /esquemas/metadatos.json {
        default_type application/json;
        try_files /esquemas/metadatos.json =404;
    }

    location = /esquemas/metadatos.jsonld {
        default_type application/ld+json;
        try_files /esquemas/metadatos.jsonld =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
